#define yy_create_buffer cu_create_buffer
#define yy_delete_buffer cu_delete_buffer
#define yy_scan_buffer cu_scan_buffer
#define yy_scan_string cu_scan_string
#define yy_scan_bytes cu_scan_bytes
#define yy_flex_debug cu_flex_debug
#define yy_init_buffer cu_init_buffer
#define yy_flush_buffer cu_flush_buffer
#define yy_load_buffer_state cu_load_buffer_state
#define yy_switch_to_buffer cu_switch_to_buffer
#define yyin cuin
#define yyleng culeng
#define yylex culex
#define yyout cuout
#define yyrestart curestart
#define yytext cutext
#define yylineno culineno

/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_acclist[334] =
    {   0,
       80,   78,   79,   77,   78,   79,   77,   79,   78,   79,
       78,   79,   78,   79,   78,   79,   78,   79,   78,   79,
       78,   79,   78,   79,   78,   79,   78,   79,   78,   79,
       43,   78,   79,   44,   78,   79,   78,   79,   78,   79,
       78,   79,   42,   78,   79,   78,   79,   78,   79,   42,
       78,   79,   42,   78,   79,   42,   78,   79,   42,   78,
       79,   42,   78,   79,   42,   78,   79,   42,   78,   79,
       42,   78,   79,   42,   78,   79,   42,   78,   79,   42,
       78,   79,   42,   78,   79,   42,   78,   79,   42,   78,
       79,   42,   78,   79,   42,   78,   79,   78,   79,   74,

       78,   79,   77,   78,   79,   78,   79,   79,   78,   79,
       78,   79,   77,   60,   50,   52,   67,   55,   70,   65,
       53,   63,   54,   64,   48,   73,   66,   47,   44,   61,
       57,   59,   58,   62,   42,   51,   71,   42,   42,   42,
       42,   42,   42,    6,   42,   42,   42,   42,   42,    9,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   72,   56,   77,   73,   75,   66,
       76,   49,   73,   47,   48,   46,   45,   68,   69,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   11,
       42,   42,   10,   42,   42,   41,   42,   42,   42,   42,

       42,   42,   42,   42,   42,   42,   42,   42,   42,   75,
       48,   47,   21,   42,   20,   42,   42,    3,   42,   34,
       42,   42,   42,   42,   42,    7,   42,   42,    8,   42,
       36,   42,   42,   16,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   33,   42,
       42,   47,   48,    2,   42,   42,   42,   42,   42,   12,
       42,   14,   42,   42,   35,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   13,   42,   42,   42,   40,   42,   37,   42,   15,
       42,   17,   42,   38,   42,   31,   42,   32,   42,   28,

       42,   25,   42,   23,   42,   18,   42,   22,   42,   42,
       42,   30,   42,   29,   42,   24,   42,   19,   42,   42,
       42,    5,   42,   27,   42,   26,   42,   42,    4,   42,
       39,   42,    1
    } ;

static yyconst short int yy_accept[264] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    7,    9,   11,   13,   15,   17,   19,   21,   23,
       25,   27,   29,   31,   34,   37,   39,   41,   43,   46,
       48,   50,   53,   56,   59,   62,   65,   68,   71,   74,
       77,   80,   83,   86,   89,   92,   95,   98,  100,  103,
      106,  108,  109,  111,  113,  114,  115,  115,  116,  116,
      117,  118,  119,  120,  120,  120,  121,  122,  123,  124,
      125,  126,  127,  128,  129,  129,  129,  129,  130,  131,
      132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  146,  147,  148,  149,  150,  152,  153,

      154,  155,  156,  157,  158,  159,  160,  161,  162,  163,
      164,  165,  166,  167,  168,  168,  168,  168,  170,  171,
      171,  171,  172,  172,  173,  173,  174,  176,  176,  176,
      177,  178,  179,  180,  181,  182,  183,  184,  185,  186,
      187,  188,  189,  190,  192,  193,  195,  196,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      210,  210,  211,  211,  211,  211,  212,  212,  212,  213,
      215,  217,  218,  220,  222,  223,  224,  225,  226,  228,
      229,  231,  233,  234,  236,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  246,  247,  248,  249,  251,  252,

      252,  252,  254,  256,  257,  258,  259,  260,  262,  264,
      265,  267,  268,  269,  270,  271,  272,  273,  274,  275,
      276,  277,  278,  279,  280,  281,  282,  284,  284,  285,
      286,  288,  290,  292,  294,  296,  298,  300,  302,  304,
      306,  308,  310,  311,  312,  314,  316,  318,  320,  321,
      321,  322,  324,  326,  328,  329,  329,  331,  333,  333,
      333,  334,  334
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,   12,   13,    1,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,    1,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   25,   24,   24,
        1,   26,    1,   27,   24,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   24,   37,   38,   39,   40,
       41,   42,   24,   43,   44,   45,   46,   47,   48,   25,
       24,   49,    1,   50,    1,   51,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    3,    3,    4,    4,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1
    } ;

static yyconst short int yy_base[275] =
    {   0,
        0,   48,    0,    0,    0,    0,   37,   50,  372,  373,
       56,   65,  351,   55,   47,  350,   52,  343,  348,   57,
       59,   57,   62,   68,   72,   77,  347,   78,    0,  326,
      345,  319,  320,   66,   39,  324,   64,  320,   70,  319,
      327,   63,  326,   76,  317,  315,  320,   64,  373,  113,
      318,  373,  102,   87,  127,  373,   82,  373,    0,  373,
      373,  373,  373,  342,    0,  373,  373,  373,  373,  373,
      115,    0,  373,  117,  127,  138,    0,  143,  332,  373,
      373,  373,  331,    0,  373,  373,  309,  317,  304,  319,
      306,  103,  299,  300,  302,  299,  296,    0,  295,  299,

      290,  301,  291,  290,  293,  105,  120,  297,  288,  295,
      294,  373,  373,  165,  293,  288,  127,    0,  148,    0,
       97,    0,  120,  373,  163,    0,  161,  169,  153,  171,
        0,  373,  373,  129,  299,  294,  282,  279,  295,  290,
      292,  288,  291,    0,  277,    0,  283,    0,  276,  271,
      268,  270,  272,  279,  265,  160,  264,  272,  276,  268,
      275,  373,  169,  165,  182,  189,  195,  193,  197,    0,
        0,  267,    0,    0,  267,  256,  256,  262,    0,  254,
        0,    0,  253,    0,  254,  251,  263,  253,  257,  188,
      252,  259,  261,  162,  175,  259,  254,    0,  255,  248,

      201,  204,    0,  245,  246,  251,  250,    0,  248,  240,
        0,  248,  245,  247,  231,  232,  232,  239,  232,  228,
      235,  230,  219,  212,  216,  203,    0,  191,  187,  181,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  188,  181,    0,    0,    0,    0,  169,  166,
      141,    0,    0,    0,  126,   93,    0,    0,  116,   89,
      373,  373,  227,  231,  235,  237,  241,  245,  249,  253,
       53,  257,  261,  265
    } ;

static yyconst short int yy_def[275] =
    {   0,
      262,    1,  263,  263,  263,  263,    1,    1,  262,  262,
      262,  262,  262,  264,  262,  262,  262,  265,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  266,  262,
      262,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  262,  262,  262,
      262,  262,  267,  268,  262,  262,  264,  262,  269,  262,
      262,  262,  262,  262,  265,  262,  262,  262,  262,  262,
      262,  270,  262,  262,  262,  262,  271,  262,  262,  262,
      262,  262,  262,  266,  262,  262,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  262,  262,  262,  262,  262,  267,  270,  267,  272,
      268,  273,  264,  262,  262,  270,  262,  262,  262,  262,
      271,  262,  262,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      262,  262,  267,  268,  262,  262,  262,  262,  262,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  262,

      262,  262,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  262,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  262,
      266,  266,  266,  266,  266,  262,  266,  266,  274,  274,
      262,    0,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262
    } ;

static yyconst short int yy_nxt[425] =
    {   0,
       10,   11,   12,   11,   13,   14,   10,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   29,   39,   29,   40,   29,   41,
       29,   42,   43,   44,   29,   45,   46,   47,   29,   48,
       49,   50,   53,   50,   51,  131,   51,   55,   55,   55,
       58,   62,   54,   60,   60,   53,   55,   55,   55,   67,
       92,   63,   69,   71,   71,   54,   68,   72,   70,   93,
       59,   73,   74,  112,   75,   75,   74,   58,   78,   78,
       76,  261,   77,   89,   76,   79,   80,   82,   83,   76,

       90,   95,   98,   76,   96,  102,   91,   59,  103,   99,
      105,  106,  122,  113,   55,   55,  114,  118,  261,  115,
      107,  119,  122,  108,  259,   58,   85,  120,   55,   55,
       55,   71,   71,  127,  127,  139,  262,  125,  153,  128,
      140,   74,  162,   75,   75,   59,  125,  155,  128,   76,
      129,  129,  120,  154,  130,  130,  258,   74,   76,   78,
       78,  170,  156,  162,  171,   76,   55,   55,  114,  130,
      130,  115,  257,  120,   76,  165,  165,  127,  127,  166,
      166,  168,  168,  167,  162,  169,  169,  130,  130,  190,
      122,  221,  167,  222,  120,  191,  256,  192,  166,  166,

      255,  193,  194,  195,  262,  166,  166,  201,  201,  169,
      169,  202,  202,  169,  169,  215,  223,  202,  202,  224,
      202,  202,  216,  254,  253,  252,  217,   52,   52,   52,
       52,   57,  251,   57,   57,   64,  250,   64,   64,   84,
       84,  117,  249,  117,  117,  121,  121,  121,  121,  123,
      248,  123,  123,  126,  247,  126,  126,  163,  246,  163,
      163,  164,  245,  164,  164,  260,  260,  260,  260,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  220,
      219,  218,  214,  213,  212,  211,  210,  209,  208,  207,

      206,  205,  204,  203,  200,  199,  198,  197,  196,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  161,  116,  160,
      159,  158,  157,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  138,  137,  136,  135,  134,
      133,  132,  124,  116,  111,  110,  109,  104,  101,  100,
       97,   94,   88,   87,   86,   85,   81,   66,   65,   61,
       56,  262,    9,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262
    } ;

static yyconst short int yy_chk[425] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    7,    8,    2,  271,    8,   11,   11,   11,
       14,   17,    7,   15,   15,    8,   12,   12,   12,   20,
       35,   17,   21,   22,   22,    8,   20,   23,   21,   35,
       14,   23,   24,   48,   24,   24,   25,   57,   25,   25,
       24,  260,   24,   34,   25,   26,   26,   28,   28,   24,

       34,   37,   39,   25,   37,   42,   34,   57,   42,   39,
       44,   44,   54,   48,   50,   50,   50,   53,  259,   50,
       44,   53,  121,   44,  256,  123,   54,   53,   55,   55,
       55,   71,   71,   74,   74,   92,  121,   71,  106,   74,
       92,   75,  117,   75,   75,  123,   71,  107,   74,   75,
       76,   76,  117,  106,   76,   76,  255,   78,   75,   78,
       78,  134,  107,  119,  134,   78,  114,  114,  114,  129,
      129,  114,  251,  119,   78,  125,  125,  127,  127,  125,
      125,  128,  128,  127,  163,  128,  128,  130,  130,  156,
      164,  194,  127,  194,  163,  156,  250,  156,  165,  165,

      249,  156,  156,  156,  164,  166,  166,  167,  167,  168,
      168,  167,  167,  169,  169,  190,  195,  201,  201,  195,
      202,  202,  190,  244,  243,  230,  190,  263,  263,  263,
      263,  264,  229,  264,  264,  265,  228,  265,  265,  266,
      266,  267,  226,  267,  267,  268,  268,  268,  268,  269,
      225,  269,  269,  270,  224,  270,  270,  272,  223,  272,
      272,  273,  222,  273,  273,  274,  274,  274,  274,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  210,
      209,  207,  206,  205,  204,  200,  199,  197,  196,  193,
      192,  191,  189,  188,  187,  186,  185,  183,  180,  178,

      177,  176,  175,  172,  161,  160,  159,  158,  157,  155,
      154,  153,  152,  151,  150,  149,  147,  145,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  116,  115,  111,
      110,  109,  108,  105,  104,  103,  102,  101,  100,   99,
       97,   96,   95,   94,   93,   91,   90,   89,   88,   87,
       83,   79,   64,   51,   47,   46,   45,   43,   41,   40,
       38,   36,   33,   32,   31,   30,   27,   19,   18,   16,
       13,    9,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cu.l"
#define INITIAL 0
#line 4 "cu.l"
#include "cu.h"
#define YYLTYPE culloc_t
#include "cu.tab.h"
#define  yylval culval
#define  yylloc culloc
#define  YY_USER_ACTION \
    cu_symbol_begin = cu_symbol_end; \
    cu_symbol_end  += yyleng;        \
    yylloc.lineno = yylineno;        \
    yylloc.begin  = cu_symbol_begin; \
    yylloc.end    = cu_symbol_end  ; \
    if(could_be_regex){              \
        --could_be_regex;            \
        if(!could_be_regex){         \
            BEGIN(0);                \
        }                            \
    }

int cu_symbol_begin;
int cu_symbol_end  ;
int cu_lexer_only=0;
int could_be_regex=0;
int comment_depth;

void _re_err(char* str, char del){
    char* ptr = str;
    int   is_atom = 0;
    vector<char*> open_parens;
    while(*ptr){ 
        switch(*ptr++)
        {
          case '*':
          case '+':
          case '?': {
              if(!is_atom){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "%c must follow an atom.\n", 
                    culineno, del, str, del, ptr[-1]);
                  return;
              }
          }
          break;

          case '{': {
              if(!is_atom){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "%c must follow an atom.\n",
                    culineno, del, str, del, ptr[-1]);
                  return;
              }
              if(!isdigit(*ptr)){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "{ must be followed by an integer.\n",
                    culineno, del, str, del);
                  return;
              }
              char* begin = ptr;
              int i = 0;
              while(isdigit(*ptr)){
                  i = i*10 + *ptr++ - '0';
              }
              if(*ptr==',' && isdigit(*++ptr)){
                  int j = 0;
                  while(isdigit(*ptr)){
                      j = j*10 + *ptr++ - '0';
                  }
                  if(i>j){
                      snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                        "invalid range.\n",
                        culineno, del, str, del);
                      return;
                  }
              }
              if(*ptr++!='}'){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "missing }.\n",
                    culineno, del, str, del);
                  return;
              }
          }
          break;

          case '|' : {
              is_atom = 0;
          }
          break;

          case ')' : {
              is_atom = 1;
              if(open_parens.size()){
                  char* left = open_parens.back();
                  open_parens.pop_back();
              }
          }
          break;

          case '(' : {
              if(!*ptr){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "trailing (.\n",
                    culineno, del, str, del);
                  return;
              }
              is_atom = 0;
              open_parens.push_back(ptr-1);
          }
          break;

          case '[' : {
              char* begin = ptr-1;
              int n=0;
              if(*ptr=='^'){
                  ptr++;
              }
              if(*ptr==']'){
                  ptr++;
                  n++;
              }
              while(*ptr && *ptr!=']'){
                  char c = ptr[1];
                  if(*ptr=='[' && (c=='.'||c=='='||c==':')){
                      char* begin = ptr+2;
                      if(ptr[2]&&ptr[3]){
                          ptr += 3;
                          while(*ptr && (*ptr!=']' || ptr[-1]!=c)) ptr++;
                          if(!*ptr){
                              snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                                "missing %c].\n",
                                culineno, del, str, del, c);
                              return;
                          }
                          ptr++;
                      }else{
                          snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                            "missing %c].\n",
                            culineno, del, str, del, c);
                          return;
                      }
                      if(c==':'){
                      }
                      if(n==2){
                          n=0;
                      }else{
                          n=1;
                      }
                  }else if(*ptr=='-'){
                      if(n==0){
                          n = 1;
                      }else if(n==1){
                          n = 2;
                          if(ptr[1]==']'){
                          }
                      }else if(n==2){
                          n=0;
                      }
                      ptr++;
                  }else{
                      if(n==2){
                          n=0;
                      }else{
                          n=1;
                      }
                      ptr++;
                  }
              }
              if(*ptr++!=']'){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "missing ].\n",
                    culineno, del, str, del);
                  return;
              }
              is_atom = 1;
          }
          break;

          case ']' : {
              is_atom = 1;
          }
          break;

          case '\\' : {
              if(!*ptr){
                  snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
                    "trailing \\.\n",
                    culineno, del, str, del);
                  return;
              }
              int match_literally = 0;
              switch(*ptr++){
                  case 'w':
                  case 'W':
                  case 's':
                  case 'S':
                  case 'b':
                  case 'B':
                  case '<':
                  case '>':
                  case '\'':
                  case '`':
                      break;
                  default:
                      match_literally = 1;
              }
              is_atom = 1;
          }
          break;
            
          default:
              is_atom = 1;
        }
    }
    if(open_parens.size()){
        char* left = open_parens.back();
        snprintf(cu_err, sizeof(cu_err), "Error, on line %d, in %c%s%c, "
          "missing ).\n",
          culineno, del, str, del);
        return;
    }
}
void re_err(){
    char c = *yytext;
    yytext[yyleng-1] = 0;
    _re_err(yytext+1, c);
    yytext[yyleng-1] = c;
}

#define CMMT 1

#define SHRP 2

#define REGX 3

#line 860 "lex.cu.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 240 "cu.l"

#line 1019 "lex.cu.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 373 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 244 "cu.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 251 "cu.l"
{ return K_break;   }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 252 "cu.l"
{ return K_case;    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 253 "cu.l"
{ return K_continue;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 254 "cu.l"
{ return K_default; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 255 "cu.l"
{ return K_do;      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 256 "cu.l"
{ return K_else;    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 257 "cu.l"
{ return K_goto;    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 258 "cu.l"
{ return K_if;      }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 259 "cu.l"
{ return K_int;     }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 260 "cu.l"
{ return K_for;     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 261 "cu.l"
{ return K_float;   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 262 "cu.l"
{ return K_while;   }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 263 "cu.l"
{ return K_print;   }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 264 "cu.l"
{ return K_printf;  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 265 "cu.l"
{ return K_puts;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 266 "cu.l"
{ return K_return;  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 267 "cu.l"
{ return K_string;  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 268 "cu.l"
{ return K_switch;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 271 "cu.l"
{ return K_atoi;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 272 "cu.l"
{ return K_atof;    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 273 "cu.l"
{ return K_strlen;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 274 "cu.l"
{ return K_strcmp;  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 275 "cu.l"
{ return K_strstr;  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 276 "cu.l"
{ return K_strchr;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 277 "cu.l"
{ return K_strrchr; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 278 "cu.l"
{ return K_strpbrk; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 279 "cu.l"
{ return K_strcat;  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 280 "cu.l"
{ return K_strspn;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 282 "cu.l"
{ return K_strref;  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 283 "cu.l"
{ return K_sizeof;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 286 "cu.l"
{return K_static  ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 287 "cu.l"
{return K_void    ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 288 "cu.l"
{return K_char    ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 289 "cu.l"
{return K_short   ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 290 "cu.l"
{return K_long    ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 291 "cu.l"
{return K_double  ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 292 "cu.l"
{return K_signed  ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 293 "cu.l"
{return K_unsigned;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 294 "cu.l"
{return K_delete  ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 295 "cu.l"
{return K_new     ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 297 "cu.l"
{
        if(cu_lexer_only) return T_id;
        symbol_name = yytext;
        return lexer_query_symbol(symbol_name);
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 303 "cu.l"
{   if(cu_lexer_only) return T_num; 
        yylval.expr = new expr_t(&expr_t::zero_int, null_expr, null_expr);
        return T_num; 
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 308 "cu.l"
{
        if(cu_lexer_only) return T_num;
        yylval.expr = new expr_t(atoi(yytext));
        return T_num; 
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 314 "cu.l"
{
        if(cu_lexer_only) return T_num; 
        int sum = 0;
        char c;
        for(int i=2; c=yytext[i]; ++i){
            sum <<= 4;
            if(c<='9'){ 
                sum += (c-'0');
            }else if(c<='F'){
                sum += (c-'A')+10;
            }else{
                sum += (c-'a')+10;
            }
        }
        yylval.expr = new expr_t(sum);
        return T_num;
    }
	YY_BREAK
case 46:
#line 333 "cu.l"
case 47:
#line 334 "cu.l"
case 48:
YY_RULE_SETUP
#line 334 "cu.l"
{
        yylval.expr = new expr_t((flt)atof(yytext));
        return T_flt;
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 339 "cu.l"
{
        if(cu_lexer_only) return T_num;
        char c=yytext[1];
        if(c=='\\'){
            c=yytext[2];
            switch(c){
              case 'a': c = '\a'; break;
              case 'f': c = '\f'; break;
              case 'n': c = '\n'; break;
              case 't': c = '\t'; break;
              case 'r': c = '\r'; break;
              case 'v': c = '\v'; break;
            }
        }
        yylval.expr = new expr_t((int)c);
        return T_num; 
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 357 "cu.l"
{
        if(cu_lexer_only) return T_str;
        string str;
        yytext[yyleng-1] = 0;
        const char* ptr = yytext;
        char c;
        while(c=*++ptr){ 
            if(c=='\\'){
                c=*++ptr;
                if(!c){
                    str.push_back('\\');
                    break;
                }else{
                    switch(c){
                      case '"': str.push_back('\"'); break;
                      case '\\':str.push_back('\\'); break;
                      case 'f': str.push_back('\f'); break;
                      case 'n': str.push_back('\n'); break;
                      case 't': str.push_back('\t'); break;
                      case 'r': str.push_back('\r'); break;
                      case 'v': str.push_back('\v'); break;
                      default:
                        str.push_back('\\');
                        str.push_back(c);
                    }
                }
            }else{
                str.push_back(c);
            }
        }
        yytext[yyleng-1] = '"';
        yylval.expr = new expr_t(new str_t(0, str.c_str()));
        return T_str;
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 393 "cu.l"
{
        if(cu_lexer_only) return T_str;
        yylval.expr = new expr_t(new str_t(1, "\n"));
        return T_str;
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 400 "cu.l"
{
        if(cu_lexer_only) return T_sub;
        yylval.expr = new expr_t(&expr_t::get_submatch_str, yytext[1]-'0');
        return T_str;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 406 "cu.l"
{return K_incr;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 407 "cu.l"
{return K_decr;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 408 "cu.l"
{return K_and ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 409 "cu.l"
{return K_or  ;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 410 "cu.l"
{return K_le  ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 411 "cu.l"
{return K_ge  ;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 412 "cu.l"
{return K_eq  ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 413 "cu.l"
{return K_ne  ;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 414 "cu.l"
{return K_sl  ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 415 "cu.l"
{return K_sr  ;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 417 "cu.l"
{return yylval.tokn=Xdd;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 418 "cu.l"
{return yylval.tokn=Xub;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 419 "cu.l"
{return yylval.tokn=Xul;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 420 "cu.l"
{return yylval.tokn=Xiv;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 421 "cu.l"
{return yylval.tokn=Xod;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 422 "cu.l"
{return yylval.tokn=Xsl;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 423 "cu.l"
{return yylval.tokn=Xsr;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 424 "cu.l"
{return yylval.tokn=Xab;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 425 "cu.l"
{return yylval.tokn=Xxb;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 426 "cu.l"
{return yylval.tokn=Xob;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 429 "cu.l"
{
        if(cu_lexer_only){
            could_be_regex += could_be_regex;
            return K_comment;
        }
    }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 470 "cu.l"
{BEGIN(REGX); could_be_regex=2; return *yytext;} 
	YY_BREAK
case 75:
#line 473 "cu.l"
case 76:
YY_RULE_SETUP
#line 473 "cu.l"
{
        if(cu_lexer_only){
            return T_regex;
        }
        char c = yytext[yyleng-1];
        yytext[yyleng-1] = 0;
        regex_t* r = (regex_t*) malloc(sizeof(regex_t));
        int status = regcomp(r, yytext+1, REG_EXTENDED);
        yytext[yyleng-1] = c;
        if(status==0){
            yylval.regx = r;
            return T_regex;
        }else{
            regfree(r);
            free(r);
            static char buf[256];
            re_err();
            yylval.emsg = NULL;
            return T_regex_err;
        }
    }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 502 "cu.l"
{ 
        could_be_regex += could_be_regex;
    }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 506 "cu.l"
{return *yytext;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 507 "cu.l"
ECHO;
	YY_BREAK
#line 1660 "lex.cu.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(CMMT):
			case YY_STATE_EOF(SHRP):
			case YY_STATE_EOF(REGX):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 262);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 507 "cu.l"


int cuparse();

int cuparse_string(string& str){
    str.push_back(0);
    cu_scan_buffer(&(str[0]), str.size()+1);
    yylineno = 1;
    cu_symbol_begin = 0;
    cu_symbol_end   = 0;
    could_be_regex  = 0;
    BEGIN(0);
    int status = cuparse();
    cu_delete_buffer(YY_CURRENT_BUFFER);
    str.resize(str.size()-1);
    return status;
}

int cuparse_string(char* str, int len){
    cu_scan_buffer(str, len+2);
    yylineno = 1;
    cu_symbol_begin = 0;
    cu_symbol_end   = 0;
    could_be_regex  = 0;
    BEGIN(0);
    int status = cuparse();
    cu_delete_buffer(YY_CURRENT_BUFFER);
    return status;
}

int culex_begin(char* str, int len){
    cu_lexer_only = 1;
    cu_scan_buffer(str, len+2);
    yylineno = 1;
    cu_symbol_begin = 0;
    cu_symbol_end   = 0;
    could_be_regex  = 0;
    BEGIN(0);
}
void culex_end(){
    cu_lexer_only = 0;
    cu_delete_buffer(YY_CURRENT_BUFFER);
}

